/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalFloridaRouteImport } from './routes/legal.florida'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthenticatedTripsRouteImport } from './routes/_authenticated.trips'
import { Route as AuthenticatedRideRouteImport } from './routes/_authenticated.ride'
import { Route as AuthenticatedPayRouteImport } from './routes/_authenticated.pay'
import { Route as AuthenticatedDriverRouteImport } from './routes/_authenticated.driver'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedBookRouteImport } from './routes/_authenticated.book'
import { Route as AuthenticatedBecomeDriverRouteImport } from './routes/_authenticated.become-driver'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated.account'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicComplaintsRouteImport } from './routes/api/public/complaints'
import { Route as AuthenticatedDriverBillingRouteImport } from './routes/_authenticated.driver.billing'
import { Route as AuthenticatedAccountSuspendedRouteImport } from './routes/_authenticated.account.suspended'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicCronCheckGracePeriodsRouteImport } from './routes/api/public/cron/check-grace-periods'
import { Route as ApiPublicCronCheckAlertsRouteImport } from './routes/api/public/cron/check-alerts'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalFloridaRoute = LegalFloridaRouteImport.update({
  id: '/legal/florida',
  path: '/legal/florida',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTripsRoute = AuthenticatedTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRideRoute = AuthenticatedRideRouteImport.update({
  id: '/ride',
  path: '/ride',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPayRoute = AuthenticatedPayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDriverRoute = AuthenticatedDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBookRoute = AuthenticatedBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBecomeDriverRoute =
  AuthenticatedBecomeDriverRouteImport.update({
    id: '/become-driver',
    path: '/become-driver',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicComplaintsRoute = ApiPublicComplaintsRouteImport.update({
  id: '/api/public/complaints',
  path: '/api/public/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDriverBillingRoute =
  AuthenticatedDriverBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedDriverRoute,
  } as any)
const AuthenticatedAccountSuspendedRoute =
  AuthenticatedAccountSuspendedRouteImport.update({
    id: '/suspended',
    path: '/suspended',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronCheckGracePeriodsRoute =
  ApiPublicCronCheckGracePeriodsRouteImport.update({
    id: '/api/public/cron/check-grace-periods',
    path: '/api/public/cron/check-grace-periods',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronCheckAlertsRoute =
  ApiPublicCronCheckAlertsRouteImport.update({
    id: '/api/public/cron/check-alerts',
    path: '/api/public/cron/check-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/become-driver': typeof AuthenticatedBecomeDriverRoute
  '/book': typeof AuthenticatedBookRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/driver': typeof AuthenticatedDriverRouteWithChildren
  '/pay': typeof AuthenticatedPayRoute
  '/ride': typeof AuthenticatedRideRoute
  '/trips': typeof AuthenticatedTripsRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/legal/florida': typeof LegalFloridaRoute
  '/account/suspended': typeof AuthenticatedAccountSuspendedRoute
  '/driver/billing': typeof AuthenticatedDriverBillingRoute
  '/api/public/complaints': typeof ApiPublicComplaintsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/cron/check-alerts': typeof ApiPublicCronCheckAlertsRoute
  '/api/public/cron/check-grace-periods': typeof ApiPublicCronCheckGracePeriodsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/become-driver': typeof AuthenticatedBecomeDriverRoute
  '/book': typeof AuthenticatedBookRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/driver': typeof AuthenticatedDriverRouteWithChildren
  '/pay': typeof AuthenticatedPayRoute
  '/ride': typeof AuthenticatedRideRoute
  '/trips': typeof AuthenticatedTripsRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/legal/florida': typeof LegalFloridaRoute
  '/account/suspended': typeof AuthenticatedAccountSuspendedRoute
  '/driver/billing': typeof AuthenticatedDriverBillingRoute
  '/api/public/complaints': typeof ApiPublicComplaintsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/cron/check-alerts': typeof ApiPublicCronCheckAlertsRoute
  '/api/public/cron/check-grace-periods': typeof ApiPublicCronCheckGracePeriodsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/become-driver': typeof AuthenticatedBecomeDriverRoute
  '/_authenticated/book': typeof AuthenticatedBookRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/driver': typeof AuthenticatedDriverRouteWithChildren
  '/_authenticated/pay': typeof AuthenticatedPayRoute
  '/_authenticated/ride': typeof AuthenticatedRideRoute
  '/_authenticated/trips': typeof AuthenticatedTripsRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/legal/florida': typeof LegalFloridaRoute
  '/_authenticated/account/suspended': typeof AuthenticatedAccountSuspendedRoute
  '/_authenticated/driver/billing': typeof AuthenticatedDriverBillingRoute
  '/api/public/complaints': typeof ApiPublicComplaintsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/cron/check-alerts': typeof ApiPublicCronCheckAlertsRoute
  '/api/public/cron/check-grace-periods': typeof ApiPublicCronCheckGracePeriodsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/verify-email'
    | '/account'
    | '/admin'
    | '/become-driver'
    | '/book'
    | '/dashboard'
    | '/driver'
    | '/pay'
    | '/ride'
    | '/trips'
    | '/email/unsubscribe'
    | '/legal/florida'
    | '/account/suspended'
    | '/driver/billing'
    | '/api/public/complaints'
    | '/lovable/email/suppression'
    | '/api/public/cron/check-alerts'
    | '/api/public/cron/check-grace-periods'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/verify-email'
    | '/account'
    | '/admin'
    | '/become-driver'
    | '/book'
    | '/dashboard'
    | '/driver'
    | '/pay'
    | '/ride'
    | '/trips'
    | '/email/unsubscribe'
    | '/legal/florida'
    | '/account/suspended'
    | '/driver/billing'
    | '/api/public/complaints'
    | '/lovable/email/suppression'
    | '/api/public/cron/check-alerts'
    | '/api/public/cron/check-grace-periods'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/verify-email'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/become-driver'
    | '/_authenticated/book'
    | '/_authenticated/dashboard'
    | '/_authenticated/driver'
    | '/_authenticated/pay'
    | '/_authenticated/ride'
    | '/_authenticated/trips'
    | '/email/unsubscribe'
    | '/legal/florida'
    | '/_authenticated/account/suspended'
    | '/_authenticated/driver/billing'
    | '/api/public/complaints'
    | '/lovable/email/suppression'
    | '/api/public/cron/check-alerts'
    | '/api/public/cron/check-grace-periods'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LegalFloridaRoute: typeof LegalFloridaRoute
  ApiPublicComplaintsRoute: typeof ApiPublicComplaintsRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicCronCheckAlertsRoute: typeof ApiPublicCronCheckAlertsRoute
  ApiPublicCronCheckGracePeriodsRoute: typeof ApiPublicCronCheckGracePeriodsRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/florida': {
      id: '/legal/florida'
      path: '/legal/florida'
      fullPath: '/legal/florida'
      preLoaderRoute: typeof LegalFloridaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trips': {
      id: '/_authenticated/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AuthenticatedTripsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ride': {
      id: '/_authenticated/ride'
      path: '/ride'
      fullPath: '/ride'
      preLoaderRoute: typeof AuthenticatedRideRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pay': {
      id: '/_authenticated/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof AuthenticatedPayRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/driver': {
      id: '/_authenticated/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof AuthenticatedDriverRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/book': {
      id: '/_authenticated/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof AuthenticatedBookRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/become-driver': {
      id: '/_authenticated/become-driver'
      path: '/become-driver'
      fullPath: '/become-driver'
      preLoaderRoute: typeof AuthenticatedBecomeDriverRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/complaints': {
      id: '/api/public/complaints'
      path: '/api/public/complaints'
      fullPath: '/api/public/complaints'
      preLoaderRoute: typeof ApiPublicComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/driver/billing': {
      id: '/_authenticated/driver/billing'
      path: '/billing'
      fullPath: '/driver/billing'
      preLoaderRoute: typeof AuthenticatedDriverBillingRouteImport
      parentRoute: typeof AuthenticatedDriverRoute
    }
    '/_authenticated/account/suspended': {
      id: '/_authenticated/account/suspended'
      path: '/suspended'
      fullPath: '/account/suspended'
      preLoaderRoute: typeof AuthenticatedAccountSuspendedRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/check-grace-periods': {
      id: '/api/public/cron/check-grace-periods'
      path: '/api/public/cron/check-grace-periods'
      fullPath: '/api/public/cron/check-grace-periods'
      preLoaderRoute: typeof ApiPublicCronCheckGracePeriodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/check-alerts': {
      id: '/api/public/cron/check-alerts'
      path: '/api/public/cron/check-alerts'
      fullPath: '/api/public/cron/check-alerts'
      preLoaderRoute: typeof ApiPublicCronCheckAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountSuspendedRoute: typeof AuthenticatedAccountSuspendedRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountSuspendedRoute: AuthenticatedAccountSuspendedRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedDriverRouteChildren {
  AuthenticatedDriverBillingRoute: typeof AuthenticatedDriverBillingRoute
}

const AuthenticatedDriverRouteChildren: AuthenticatedDriverRouteChildren = {
  AuthenticatedDriverBillingRoute: AuthenticatedDriverBillingRoute,
}

const AuthenticatedDriverRouteWithChildren =
  AuthenticatedDriverRoute._addFileChildren(AuthenticatedDriverRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBecomeDriverRoute: typeof AuthenticatedBecomeDriverRoute
  AuthenticatedBookRoute: typeof AuthenticatedBookRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDriverRoute: typeof AuthenticatedDriverRouteWithChildren
  AuthenticatedPayRoute: typeof AuthenticatedPayRoute
  AuthenticatedRideRoute: typeof AuthenticatedRideRoute
  AuthenticatedTripsRoute: typeof AuthenticatedTripsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBecomeDriverRoute: AuthenticatedBecomeDriverRoute,
  AuthenticatedBookRoute: AuthenticatedBookRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDriverRoute: AuthenticatedDriverRouteWithChildren,
  AuthenticatedPayRoute: AuthenticatedPayRoute,
  AuthenticatedRideRoute: AuthenticatedRideRoute,
  AuthenticatedTripsRoute: AuthenticatedTripsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LegalFloridaRoute: LegalFloridaRoute,
  ApiPublicComplaintsRoute: ApiPublicComplaintsRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicCronCheckAlertsRoute: ApiPublicCronCheckAlertsRoute,
  ApiPublicCronCheckGracePeriodsRoute: ApiPublicCronCheckGracePeriodsRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
